{% set name = "chorddiag" %}
{% set version = "0.1.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-chorddiag
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/mattflor/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7569cdeee85a967475655fd130ecc31e6d80e881964e90901d69f565487eff24

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip  # [win]
  host:
    - r-base
    - r-htmlwidgets
    - r-rcolorbrewer
    - openjdk
  run:
    - r-base
    - r-htmlwidgets
    - r-rcolorbrewer
    - openjdk

test:
  commands:
    - $R -e "library('chorddiag')"           # [not win]
    - "\"%R%\" -e \"library('chorddiag')\""  # [win]

about:
  home: https://github.com/mattflor/chorddiag
  license: GPL (>= 3)
  summary: R interface to D3 chord diagrams.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - benhuff
    - conda-forge/r
